import type { NextPage } from 'next'
import React, { useState } from 'react'
import Head from 'next/head'
import Button from '../../globals/components/button/Button'
import Input from '../../globals/components/input/Input'

import styles from './login.module.scss'

import { postRequest } from "../../api";
import ENDPOINTS from '../../api/endpoints'
import AuthenticationService from '../../services/Authentication.service'
import { useDispatch } from 'react-redux'
import { setToken } from "../../redux/slicer";

const LoginPage: NextPage = () => {

    const [username, setUsername] = useState('');
    const [password, setPassword] = useState('');

    const dispatch = useDispatch()

    function handleUsernameChange(event: React.ChangeEvent<HTMLInputElement>) {
        setUsername(event.target.value)
    }

    function handlePasswordChange(event: React.ChangeEvent<HTMLInputElement>) {
        setPassword(event.target.value)
    }

    async function login(event: React.MouseEvent) {
        try {
            event.preventDefault()
            const body = { username, password };
            const { access_token } = await postRequest(ENDPOINTS.auth.login, body);
            if (access_token) {
                AuthenticationService.login(access_token);
                dispatch(setToken(access_token))
            }
        } catch (error) {
            console.error(error);
        }
    }

    return (
        <div className={styles.container}>
            <Head>
                <title>Login</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className={styles.main}>
                <div className={styles.loginForm}>
                    <h5>Login to your account</h5>
                    <Input placeholder='Username' value={username} onChange={handleUsernameChange} />
                    <Input placeholder='Password' value={password} onChange={handlePasswordChange} type='password' />
                    <Button title='Login' onClick={login} />
                </div>
            </div>

        </div>
    )
}

export default LoginPage
